// src/components/CountdownTimer.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { Clock } from 'lucide-vue-next'

const props = defineProps({
  endTime: { type: Date, required: true },
  compact: { type: Boolean, default: false },
})

const timeLeft = ref('')

function updateTimer() {
  const now = Date.now()
  const distance = props.endTime.getTime() - now

  if (distance < 0) {
    timeLeft.value = 'Ended'
    return
  }

  const days = Math.floor(distance / (1000 * 60 * 60 * 24))
  const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60))
  const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))

  if (props.compact) {
    if (days > 0) {
      timeLeft.value = `${days}d ${hours}h`
    } else if (hours > 0) {
      timeLeft.value = `${hours}h ${minutes}m`
    } else {
      timeLeft.value = `${minutes}m`
    }
  } else {
    timeLeft.value = `${days}d ${hours}h ${minutes}m`
  }
}

let interval

onMounted(() => {
  updateTimer()
  interval = setInterval(updateTimer, 60000)
})

onUnmounted(() => {
  clearInterval(interval)
})

watch(() => [props.endTime, props.compact], updateTimer)
</script>

<template>
  <div class="inline-flex items-center gap-1.5 text-muted-foreground">
    <Clock class="w-4 h-4" />
    <span :class="timeLeft === 'Ended' ? 'text-red-500' : ''">{{ timeLeft }}</span>
  </div>
</template>

// src/components/CountdownTimer.tsx
import React, { useState, useEffect } from 'react';
import { Clock } from 'lucide-react';

interface CountdownTimerProps {
  endTime: Date;
  compact?: boolean;
}

export function CountdownTimer({ endTime, compact = false }: CountdownTimerProps) {
  const [timeLeft, setTimeLeft] = useState('');
  
  useEffect(() => {
    const updateTimer = () => {
      const now = new Date().getTime();
      const distance = endTime.getTime() - now;
      
      if (distance < 0) {
        setTimeLeft('Ended');
        return;
      }
      
      const days = Math.floor(distance / (1000 * 60 * 60 * 24));
      const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      
      if (compact) {
        if (days > 0) {
          setTimeLeft(`${days}d ${hours}h`);
        } else if (hours > 0) {
          setTimeLeft(`${hours}h ${minutes}m`);
        } else {
          setTimeLeft(`${minutes}m`);
        }
      } else {
        setTimeLeft(`${days}d ${hours}h ${minutes}m`);
      }
    };
    
    updateTimer();
    const interval = setInterval(updateTimer, 60000);
    
    return () => clearInterval(interval);
  }, [endTime, compact]);
  
  return (
    <div className="inline-flex items-center gap-1.5 text-muted-foreground">
      <Clock className="w-4 h-4" />
      <span className={timeLeft === 'Ended' ? 'text-red-500' : ''}>{timeLeft}</span>
    </div>
  );
}
