// src/components/Dashboard.tsx
import React from 'react';
import { Home, ListTodo, TrendingUp, Vault, Users, Wallet, LogOut, Menu, X } from 'lucide-react';
import { GlassCard } from './GlassCard';
import { ReputationBadge } from './ReputationBadge';
import { type User } from '../lib/mockData';
import { mockTasks, mockPredictionMarkets } from '../lib/mockData';
import { TaskCard } from './TaskCard';
import { PredictionCard } from './PredictionCard';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';

interface DashboardProps {
  user: User;
  onDisconnect: () => void;
  onNavigate: (page: string) => void;
}

export function Dashboard({ user, onDisconnect, onNavigate }: DashboardProps) {
  const [sidebarOpen, setSidebarOpen] = React.useState(false);

  const myTasks = mockTasks.filter(t => t.status === 'joined');
  const myPredictions = mockPredictionMarkets.slice(0, 2);

  const mockWinRateData = [
    { month: 'Jan', rate: 60 },
    { month: 'Feb', rate: 65 },
    { month: 'Mar', rate: 62 },
    { month: 'Apr', rate: 68 },
    { month: 'May', rate: 70 },
    { month: 'Jun', rate: 68.5 }
  ];

  const tokenData = [
    { name: 'DHC', value: user.dhcBalance, color: '#00D1FF' },
    { name: 'Emotion', value: user.emotionBalance, color: '#7C3AED' },
    { name: 'Intellectual', value: user.intellectualBalance, color: '#00FF9D' }
  ];

  const NavItem = ({ icon: Icon, label, page }: { icon: any; label: string; page?: string }) => (
    <button
      onClick={() => page && onNavigate(page)}
      className="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-white/5 transition-colors text-left"
    >
      <Icon className="w-5 h-5" />
      <span>{label}</span>
    </button>
  );

  const Sidebar = ({ mobile = false }: { mobile?: boolean }) => (
    <div className={`${mobile ? 'fixed inset-0 z-50 bg-black/80 backdrop-blur-sm' : ''}`}>
      <div className={`
        ${mobile ? 'fixed top-0 left-0 h-full w-64 glass' : 'w-64'}
        flex flex-col p-6 space-y-6
      `}>
        {mobile && (
          <button
            onClick={() => setSidebarOpen(false)}
            className="absolute top-4 right-4 text-muted-foreground hover:text-foreground"
          >
            <X className="w-6 h-6" />
          </button>
        )}

        <div className="flex items-center gap-3">
          <div className="w-12 h-12 bg-gradient-to-br from-[#00D1FF] to-[#7C3AED] rounded-full flex items-center justify-center text-2xl">
            {user.avatar}
          </div>
          <div>
            <div>{user.name}</div>
            <div className="text-xs text-muted-foreground">{user.address.slice(0, 6)}...{user.address.slice(-4)}</div>
          </div>
        </div>

        <ReputationBadge score={user.reputation} size="lg" />

        <nav className="flex-1 space-y-1">
          <NavItem icon={Home} label="Dashboard" page="dashboard" />
          <NavItem icon={ListTodo} label="Tasks" page="tasks" />
          <NavItem icon={TrendingUp} label="Predictions" page="predictions" />
          <NavItem icon={Vault} label="Vault" page="vault" />
          <NavItem icon={Users} label="Community" page="community" />
          <NavItem icon={Wallet} label="Wallet" page="dashboard" />
        </nav>

        <button
          onClick={onDisconnect}
          className="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-red-500/10 text-red-500 transition-colors"
        >
          <LogOut className="w-5 h-5" />
          <span>Disconnect</span>
        </button>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen flex">
      {/* Desktop Sidebar */}
      <aside className="hidden lg:block glass border-r border-white/10">
        <Sidebar />
      </aside>

      {/* Mobile Sidebar */}
      {sidebarOpen && <Sidebar mobile />}

      {/* Main Content */}
      <main className="flex-1">
        {/* Mobile Header */}
        <div className="lg:hidden glass border-b border-white/10 p-4 flex items-center justify-between">
          <button onClick={() => setSidebarOpen(true)}>
            <Menu className="w-6 h-6" />
          </button>
          <h2>Dashboard</h2>
          <div className="w-6" />
        </div>

        <div className="p-6 max-w-7xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl mb-2">Welcome back, {user.name}!</h1>
            <p className="text-muted-foreground">Here's your activity overview</p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            <GlassCard>
              <div className="text-sm text-muted-foreground mb-2">DHC Balance</div>
              <div className="text-2xl text-[#00D1FF]">{user.dhcBalance.toLocaleString()}</div>
              <div className="text-xs text-muted-foreground mt-1">+12.5% this month</div>
            </GlassCard>
            <GlassCard>
              <div className="text-sm text-muted-foreground mb-2">Tasks Completed</div>
              <div className="text-2xl">{user.tasksCompleted}</div>
              <div className="text-xs text-[#00FF9D] mt-1">+5 this week</div>
            </GlassCard>
            <GlassCard>
              <div className="text-sm text-muted-foreground mb-2">Win Rate</div>
              <div className="text-2xl">{user.predictionWinRate}%</div>
              <div className="text-xs text-[#00FF9D] mt-1">+2.3% improvement</div>
            </GlassCard>
            <GlassCard>
              <div className="text-sm text-muted-foreground mb-2">Reputation Score</div>
              <div className="text-2xl">{user.reputation}</div>
              <ReputationBadge score={user.reputation} size="sm" />
            </GlassCard>
          </div>

          {/* Charts Row */}
          <div className="grid lg:grid-cols-2 gap-6 mb-8">
            <GlassCard>
              <h3 className="mb-4">Prediction Win Rate Trend</h3>
              <ResponsiveContainer width="100%" height={200}>
                <LineChart data={mockWinRateData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="month" stroke="#8b92a8" />
                  <YAxis stroke="#8b92a8" />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#1a1f2e', border: '1px solid rgba(255,255,255,0.1)' }}
                  />
                  <Line type="monotone" dataKey="rate" stroke="#00D1FF" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </GlassCard>

            <GlassCard>
              <h3 className="mb-4">Token Distribution</h3>
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie
                    data={tokenData}
                    cx="50%"
                    cy="50%"
                    innerRadius={50}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {tokenData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{ backgroundColor: '#1a1f2e', border: '1px solid rgba(255,255,255,0.1)' }}
                  />
                </PieChart>
              </ResponsiveContainer>
              <div className="flex justify-center gap-6 mt-4">
                {tokenData.map((token) => (
                  <div key={token.name} className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full" style={{ backgroundColor: token.color }}></div>
                    <span className="text-sm">{token.name}: {token.value}</span>
                  </div>
                ))}
              </div>
            </GlassCard>
          </div>

          {/* Active Tasks */}
          <div className="mb-8">
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl">My Active Tasks</h2>
              <button
                onClick={() => onNavigate('tasks')}
                className="text-[#00D1FF] hover:text-[#00B8E6] transition-colors"
              >
                View All →
              </button>
            </div>
            {myTasks.length > 0 ? (
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                {myTasks.map(task => (
                  <TaskCard key={task.id} task={task} onClick={() => onNavigate('tasks')} />
                ))}
              </div>
            ) : (
              <GlassCard>
                <div className="text-center py-8 text-muted-foreground">
                  <ListTodo className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p>No active tasks yet. Start by joining a task!</p>
                  <button
                    onClick={() => onNavigate('tasks')}
                    className="mt-4 text-[#00D1FF] hover:text-[#00B8E6]"
                  >
                    Browse Tasks
                  </button>
                </div>
              </GlassCard>
            )}
          </div>

          {/* My Predictions */}
          <div>
            <div className="flex justify-between items-center mb-6">
              <h2 className="text-2xl">My Predictions</h2>
              <button
                onClick={() => onNavigate('predictions')}
                className="text-[#00D1FF] hover:text-[#00B8E6] transition-colors"
              >
                View All →
              </button>
            </div>
            <div className="grid md:grid-cols-2 gap-6">
              {myPredictions.map(market => (
                <PredictionCard key={market.id} market={market} onClick={() => onNavigate('predictions')} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

// src/components/Dashboard.vue
<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Home, ListTodo, TrendingUp, Vault, Users, Wallet, LogOut, Menu, X } from 'lucide-vue-next'
import { Line, Pie } from 'vue-chartjs'
import {
  Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement,
  ArcElement, Tooltip, Legend, Filler
} from 'chart.js'
import GlassCard from './GlassCard.vue'
import ReputationBadge from './ReputationBadge.vue'
import TaskCard from './TaskCard.vue'
import PredictionCard from './PredictionCard.vue'
import { mockTasks, mockPredictionMarkets } from '@/lib/mockData'
import { useWallet } from '@/composables/useWallet'
import { toast } from 'vue-sonner'

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, ArcElement, Tooltip, Legend, Filler)

const router = useRouter()
const { user, disconnect } = useWallet()

const sidebarOpen = ref(false)

const myTasks = computed(() => mockTasks.filter(t => t.status === 'joined'))
const myPredictions = computed(() => mockPredictionMarkets.slice(0, 2))

const mockWinRateData = [
  { month: 'Jan', rate: 60 },
  { month: 'Feb', rate: 65 },
  { month: 'Mar', rate: 62 },
  { month: 'Apr', rate: 68 },
  { month: 'May', rate: 70 },
  { month: 'Jun', rate: 68.5 },
]

const lineChartData = computed(() => ({
  labels: mockWinRateData.map(d => d.month),
  datasets: [{
    data: mockWinRateData.map(d => d.rate),
    borderColor: '#00D1FF',
    borderWidth: 2,
    tension: 0.3,
    fill: false,
    pointBackgroundColor: '#00D1FF',
    pointRadius: 3,
  }],
}))

const lineChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: { legend: { display: false }, tooltip: { backgroundColor: '#1a1f2e' } },
  scales: {
    x: { ticks: { color: '#8b92a8' }, grid: { color: 'rgba(255,255,255,0.1)' } },
    y: { ticks: { color: '#8b92a8' }, grid: { color: 'rgba(255,255,255,0.1)' } },
  },
}

const tokenData = computed(() => {
  if (!user.value) return []
  return [
    { name: 'DHC', value: user.value.dhcBalance, color: '#00D1FF' },
    { name: 'Emotion', value: user.value.emotionBalance, color: '#7C3AED' },
    { name: 'Intellectual', value: user.value.intellectualBalance, color: '#00FF9D' },
  ]
})

const pieChartData = computed(() => ({
  labels: tokenData.value.map(t => t.name),
  datasets: [{
    data: tokenData.value.map(t => t.value),
    backgroundColor: tokenData.value.map(t => t.color),
    borderWidth: 0,
    spacing: 4,
  }],
}))

const pieChartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  cutout: '60%',
  plugins: { legend: { display: false }, tooltip: { backgroundColor: '#1a1f2e' } },
}

function handleDisconnect() {
  disconnect()
  router.push('/')
  toast.info('Disconnected from wallet')
}

const navItems = [
  { icon: Home, label: 'Dashboard', path: '/dashboard' },
  { icon: ListTodo, label: 'Tasks', path: '/tasks' },
  { icon: TrendingUp, label: 'Predictions', path: '/predictions' },
  { icon: Vault, label: 'Vault', path: '/vault' },
  { icon: Users, label: 'Community', path: '/community' },
  { icon: Wallet, label: 'Wallet', path: '/dashboard' },
]
</script>

<template>
  <div v-if="user" class="min-h-screen flex">
    <!-- Desktop Sidebar -->
    <aside class="hidden lg:block glass border-r border-white/10">
      <div class="w-64 flex flex-col p-6 space-y-6">
        <div class="flex items-center gap-3">
          <div class="w-12 h-12 bg-gradient-to-br from-[#00D1FF] to-[#7C3AED] rounded-full flex items-center justify-center text-2xl">
            {{ user.avatar }}
          </div>
          <div>
            <div>{{ user.name }}</div>
            <div class="text-xs text-muted-foreground">{{ user.address.slice(0, 6) }}...{{ user.address.slice(-4) }}</div>
          </div>
        </div>

        <ReputationBadge :score="user.reputation" size="lg" />

        <nav class="flex-1 space-y-1">
          <button
            v-for="item in navItems"
            :key="item.label"
            @click="router.push(item.path)"
            class="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-white/5 transition-colors text-left"
          >
            <component :is="item.icon" class="w-5 h-5" />
            <span>{{ item.label }}</span>
          </button>
        </nav>

        <button
          @click="handleDisconnect"
          class="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-red-500/10 text-red-500 transition-colors"
        >
          <LogOut class="w-5 h-5" />
          <span>Disconnect</span>
        </button>
      </div>
    </aside>

    <!-- Mobile Sidebar Overlay -->
    <div v-if="sidebarOpen" class="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm lg:hidden" @click="sidebarOpen = false">
      <div class="fixed top-0 left-0 h-full w-64 glass flex flex-col p-6 space-y-6" @click.stop>
        <button @click="sidebarOpen = false" class="absolute top-4 right-4 text-muted-foreground hover:text-foreground">
          <X class="w-6 h-6" />
        </button>

        <div class="flex items-center gap-3">
          <div class="w-12 h-12 bg-gradient-to-br from-[#00D1FF] to-[#7C3AED] rounded-full flex items-center justify-center text-2xl">
            {{ user.avatar }}
          </div>
          <div>
            <div>{{ user.name }}</div>
            <div class="text-xs text-muted-foreground">{{ user.address.slice(0, 6) }}...{{ user.address.slice(-4) }}</div>
          </div>
        </div>

        <ReputationBadge :score="user.reputation" size="lg" />

        <nav class="flex-1 space-y-1">
          <button
            v-for="item in navItems"
            :key="item.label"
            @click="router.push(item.path); sidebarOpen = false"
            class="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-white/5 transition-colors text-left"
          >
            <component :is="item.icon" class="w-5 h-5" />
            <span>{{ item.label }}</span>
          </button>
        </nav>

        <button
          @click="handleDisconnect"
          class="w-full flex items-center gap-3 px-4 py-3 rounded-lg hover:bg-red-500/10 text-red-500 transition-colors"
        >
          <LogOut class="w-5 h-5" />
          <span>Disconnect</span>
        </button>
      </div>
    </div>

    <!-- Main Content -->
    <main class="flex-1">
      <!-- Mobile Header -->
      <div class="lg:hidden glass border-b border-white/10 p-4 flex items-center justify-between">
        <button @click="sidebarOpen = true">
          <Menu class="w-6 h-6" />
        </button>
        <h2>Dashboard</h2>
        <div class="w-6" />
      </div>

      <div class="p-6 max-w-7xl mx-auto">
        <div class="mb-8">
          <h1 class="text-3xl mb-2">Welcome back, {{ user.name }}!</h1>
          <p class="text-muted-foreground">Here's your activity overview</p>
        </div>

        <!-- Stats Grid -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <GlassCard>
            <div class="text-sm text-muted-foreground mb-2">DHC Balance</div>
            <div class="text-2xl text-[#00D1FF]">{{ user.dhcBalance.toLocaleString() }}</div>
            <div class="text-xs text-muted-foreground mt-1">+12.5% this month</div>
          </GlassCard>
          <GlassCard>
            <div class="text-sm text-muted-foreground mb-2">Tasks Completed</div>
            <div class="text-2xl">{{ user.tasksCompleted }}</div>
            <div class="text-xs text-[#00FF9D] mt-1">+5 this week</div>
          </GlassCard>
          <GlassCard>
            <div class="text-sm text-muted-foreground mb-2">Win Rate</div>
            <div class="text-2xl">{{ user.predictionWinRate }}%</div>
            <div class="text-xs text-[#00FF9D] mt-1">+2.3% improvement</div>
          </GlassCard>
          <GlassCard>
            <div class="text-sm text-muted-foreground mb-2">Reputation Score</div>
            <div class="text-2xl">{{ user.reputation }}</div>
            <ReputationBadge :score="user.reputation" size="sm" />
          </GlassCard>
        </div>

        <!-- Charts Row -->
        <div class="grid lg:grid-cols-2 gap-6 mb-8">
          <GlassCard>
            <h3 class="mb-4">Prediction Win Rate Trend</h3>
            <div style="height: 200px">
              <Line :data="lineChartData" :options="lineChartOptions" />
            </div>
          </GlassCard>

          <GlassCard>
            <h3 class="mb-4">Token Distribution</h3>
            <div style="height: 200px">
              <Pie :data="pieChartData" :options="pieChartOptions" />
            </div>
            <div class="flex justify-center gap-6 mt-4">
              <div v-for="token in tokenData" :key="token.name" class="flex items-center gap-2">
                <div class="w-3 h-3 rounded-full" :style="{ backgroundColor: token.color }"></div>
                <span class="text-sm">{{ token.name }}: {{ token.value }}</span>
              </div>
            </div>
          </GlassCard>
        </div>

        <!-- Active Tasks -->
        <div class="mb-8">
          <div class="flex justify-between items-center mb-6">
            <h2 class="text-2xl">My Active Tasks</h2>
            <button @click="router.push('/tasks')" class="text-[#00D1FF] hover:text-[#00B8E6] transition-colors">
              View All →
            </button>
          </div>
          <div v-if="myTasks.length > 0" class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <TaskCard v-for="task in myTasks" :key="task.id" :task="task" @click="router.push('/tasks')" />
          </div>
          <GlassCard v-else>
            <div class="text-center py-8 text-muted-foreground">
              <ListTodo class="w-12 h-12 mx-auto mb-4 opacity-50" />
              <p>No active tasks yet. Start by joining a task!</p>
              <button @click="router.push('/tasks')" class="mt-4 text-[#00D1FF] hover:text-[#00B8E6]">
                Browse Tasks
              </button>
            </div>
          </GlassCard>
        </div>

        <!-- My Predictions -->
        <div>
          <div class="flex justify-between items-center mb-6">
            <h2 class="text-2xl">My Predictions</h2>
            <button @click="router.push('/predictions')" class="text-[#00D1FF] hover:text-[#00B8E6] transition-colors">
              View All →
            </button>
          </div>
          <div class="grid md:grid-cols-2 gap-6">
            <PredictionCard
              v-for="market in myPredictions"
              :key="market.id"
              :market="market"
              @click="router.push('/predictions')"
            />
          </div>
        </div>
      </div>
    </main>
  </div>
</template>
